version: "3"
services:
  nginx:
    build: ${API_GATEWAY:-.}/scripts/docker/nginx
    image: forforeach/attracker-nginx
    links:
      - api
    ports:
      - "3000:80"
  api:
    build: .
    image: forforeach/attracker-api
    volumes:
      - ${API_GATEWAY:-.}:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: dev
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "9222:9222"
  mongo:
    image: mongo
    volumes:
      - storage:/data/db
    ports:
      - "27017:27017"
volumes:
  storage:
